### ISSUE TITLE
[Feature Request] 加入翻译功能

### ISSUE THREAD

**Issue by pingren** [IronKinoko/youtube-danmaku#2]
可以加入自动机翻弹幕的功能吗？

**Comment by IronKinoko** [comment]
好，我试试看

**Comment by IronKinoko** [comment]
@Pingren 不太行，测了谷歌的两个接口，结果跨域，还有接口限制并发了

**Comment by pingren** [comment]
@IronKinoko 可以参考一下这个 UserScript 的实现

使用 Google Chrome 的翻译工具，自动翻译 bilibili 的用户评论(弹幕)：

https://greasyfork.org/zh-CN/scripts/384708-bilibili-danmaku-translator
