### ISSUE TITLE
兼容新版本chrome

### ISSUE THREAD

**Issue by lpylpyleo** [IronKinoko/youtube-danmaku#3]
需要在开头加一行
```
if (window.trustedTypes && window.trustedTypes.createPolicy) {  
    window.trustedTypes.createPolicy('default', {  
        createHTML: (string, sink) => string  
    }); 
}
```

https://github.com/Tampermonkey/tampermonkey/issues/1334#issuecomment-927277844
https://greasyfork.org/en/discussions/development/220765-this-document-requires-trustedhtml-assignment

**Comment by IronKinoko** [comment]
处理了，感谢反馈
